package com.workseasy.com.ui

data class Company(

    val auth_person_mob_no: String,
    val auth_person_name: String,
    val company_address: String,
    val company_adhar: String,
    val company_cin: String,
    val company_city_id: Int,
    val company_code: String,
    val company_district_id: Int,
    val company_email: String,
    val company_logo: String,
    val company_mobile: String,
    val company_name: String,
    val company_id: Int,
    val branch_id: Int,
    val company_pan: String,
    val company_pincode: Int,
    val company_registration_certificate: Any,
    val company_state_id: Int,
    val created_at: String,
    val deleted_at: Any,
    val employer_address: String,
    val employer_city_id: Int,
    val employer_district_id: Int,
    val employer_email: String,
    val employer_mob_no: String,
    val employer_name: String,
    val employer_pincode: String,
    val employer_state_id: Int,
    val esic_login_id: String,
    val esic_login_pwd: String,
    val esic_registration_certificate: Any,
    val esic_registration_no: String,
    val gst_login_id: String,
    val gst_login_password: String,
    val gst_registration_certificate: Any,
    val gst_registration_no: String,
    val id: Int,
    val pf_login_id: String,
    val pf_login_pwd: String,
    val pf_registration_certificate: Any,
    val pf_registration_no: String,
    val status: String,
    val updated_at: String
)